coordinator=true
hbo.redis-provider.server_uri=redis://localhost:6379/1
hbo.redis-provider.total-fetch-timeoutms=5000
hbo.redis-provider.total-set-timeoutms=5000
hbo.redis-provider.default-ttl-seconds=3600
hbo.redis-provider.enabled=true
hbo.redis-provider.cluster-mode-enabled=false
hbo.redis-provider.redis-password=yourpassword
hbo.redis-provider.redis-username=default
